### ISSUE TITLE
error in PharmacoGx Vignette

### ISSUE THREAD

**Issue by biovitus** [bhklab/PharmacoGx#1]
Dear Sir/Madam,

I am trying to run the code from the PharmacoGX Vignette in R and it gives the error mentioned below.
I like to know why the intersect function is giving this error and if you can help in fixing it.

commonGenes <- intersect(featureNames(GDSCsmall, "rna"), featureNames(CCLEsmall,"rna"))
Error in intersect(featureNames(GDSCsmall, "rna"), featureNames(CCLEsmall,  : 
  error in evaluating the argument 'x' in selecting a method for function 'intersect': Error in featureNames(GDSCsmall, "rna") : unused argument ("rna")

Appreciate your help,

Thank You,

 biovitus

**Comment by bhaibeka** [comment]
Thanks for your feedback. Can you install the new version 1.1.4 and try again. It works on my system.

**Comment by biovitus** [comment]
Dear Bhaibeka,

Thank you for your reply. I had installed PharmacoGx_1.1.4.tar.gz  on linux fedora 64bit and still gives the same error.

>library(PharmacoGx)
> CCLEsmall
Name:  CCLE 
Date Created:  Fri Nov  6 14:00:53 2015 
Number of cell lines:  1061 
Number of drug compounds:  24 
RNA: 
	Dim:  50 1036 
RNASeq: 
	Dim:  50 935 
CNV: 
	Dim:  50 744 
Drug pertubation: 
	Please look at pertNumber(pSet) to determine number of experiments for each drug-cell combination.
Drug sensitivity: 
	Number of Experiments:  11670 
	Please look at sensNumber(pSet) to determine number of experiments for each drug-cell combination.
> GDSCsmall
Name:  GDSC 
Date Created:  Mon Aug 24 15:18:23 2015 
Number of cell lines:  10 
Number of drug compounds:  139 
RNA: 
	Dim:  300 11 
Drug pertubation: 
	Please look at pertNumber(pSet) to determine number of experiments for each drug-cell combination.
Drug sensitivity: 
	Number of Experiments:  972 
	Please look at sensNumber(pSet) to determine number of experiments for each drug-cell combination.
> commonGenes <- intersect(featureNames(GDSCsmall, "rna"),
+ featureNames(CCLEsmall, "rna"))
Error in intersect(featureNames(GDSCsmall, "rna"), featureNames(CCLEsmall,  : 
  error in evaluating the argument 'x' in selecting a method for function 'intersect': Error in featureNames(GDSCsmall, "rna") : unused argument ("rna")
 
Appreciate your help.

Thank you.

Biovitus

**Comment by Zeenia** [comment]
Hello,
I am getting same error "Error in featureNames(GDSCsmall, "rna") : unused argument ("rna")" while trying PharmacoGx vignette on Windows and using package version 1.1.4
> library(PharmacoGx)
Warning: namespace ‘limma’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
Warning: namespace ‘limma’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
Warning: namespace ‘limma’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
Warning: namespace ‘limma’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
Warning messages:
1: replacing previous import ‘BiocGenerics::union’ by ‘igraph::union’ when loading ‘piano’ 
2: replacing previous import ‘BiocGenerics::normalize’ by ‘igraph::normalize’ when loading ‘piano’ 
> availablePSets()
trying URL 'https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/PSets.csv'
Content type 'text/csv' length 872 bytes
downloaded 872 bytes

          PSet.Name Dataset.Type Available.Molecular.Profiles             Date.Updated
GDSC           GDSC  sensitivity rna/rna2/mutation/fusion/cnv Wed Dec 30 10:44:21 2015
CCLE           CCLE  sensitivity      rna/rnaseq/mutation/cnv Thu Dec 10 18:17:14 2015
CMAP           CMAP perturbation                          rna Mon Sep 21 02:38:45 2015
GDSC_2013 GDSC_2013  sensitivity                 rna/mutation Mon Oct  5 16:07:54 2015
CCLE_2013 CCLE_2013  sensitivity                 rna/mutation Tue Sep 15 18:50:07 2015
                                                                                           URL
GDSC                 https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/GDSC.RData
CCLE                 https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/CCLE.RData
CMAP              https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/CMAP_BA.RData
GDSC_2013  https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/CGP_Nature2013.RData
CCLE_2013 https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/CCLE_Nature2013.RData
> GDSC <- downloadPSet("GDSC")
trying URL 'https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/PSets.csv'
Content type 'text/csv' length 872 bytes
downloaded 872 bytes

trying URL 'https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/GDSC.RData'
Content type '¸'Dÿþ' length 240887444 bytes (229.7 MB)
downloaded 229.7 MB
> library(Biobase)
Loading required package: BiocGenerics
Loading required package: parallel
Attaching package: ‘BiocGenerics’
The following objects are masked from ‘package:parallel’:
    clusterApply, clusterApplyLB,
    clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply,
    parCapply, parLapply, parLapplyLB,
    parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame,
    as.vector, cbind, colnames, do.call,
    duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect,
    is.unsorted, lapply, lengths, Map,
    mapply, match, mget, order, paste, pmax,
    pmax.int, pmin, pmin.int, Position,
    rank, rbind, Reduce, rownames, sapply,
    setdiff, sort, table, tapply, union,
    unique, unlist, unsplit

Welcome to Bioconductor

    Vignettes contain introductory material;
    view with 'browseVignettes()'. To cite
    Bioconductor, see 'citation("Biobase")',
    and for packages 'citation("pkgname")'.
Attaching package: ‘Biobase’
The following object is masked from ‘package:PharmacoGx’:

    featureNames

> library(PharmacoGx)
> data("GDSCsmall")
> data("CCLEsmall")
> commonGenes <- intersect(featureNames(GDSCsmall, "rna"),featureNames(CCLEsmall,"rna"))
Error in featureNames(GDSCsmall, "rna") : unused argument ("rna")
> GDSCsmall
Name:  GDSC 
Date Created:  Mon Aug 24 15:18:23 2015 
Number of cell lines:  10 
Number of drug compounds:  139 
RNA: 
	Dim:  300 11 
Drug pertubation: 
	Please look at pertNumber(pSet) to determine number of experiments for each drug-cell combination.
Drug sensitivity: 
	Number of Experiments:  972 
	Please look at sensNumber(pSet) to determine number of experiments for each drug-cell combination.
> featureNames(GDSCsmall, "rna")
Error in featureNames(GDSCsmall, "rna") : unused argument ("rna")
> sessionInfo()
R version 3.2.5 (2016-04-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252    LC_MONETARY=English_India.1252
[4] LC_NUMERIC=C                   LC_TIME=English_India.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Biobase_2.30.0       BiocGenerics_0.16.1  PharmacoGx_1.1.4     BiocInstaller_1.20.1

loaded via a namespace (and not attached):
 [1] relations_0.6-6    gtools_3.5.0       piano_1.10.2       digest_0.6.9       slam_0.1-32       
 [6] bitops_1.0-6       MASS_7.3-45        magrittr_1.5       KernSmooth_2.23-15 gplots_3.0.1      
[11] sm_2.2-5.4         gdata_2.17.0       sets_1.0-16        magicaxis_1.9.4    RColorBrewer_1.1-2
[16] tools_3.2.5        downloader_0.4     igraph_1.0.1       plotrix_3.6-1      cluster_2.0.3     
[21] marray_1.48.0      caTools_1.17.1    
> packageVersion('Pharmacogx')
[1] ‘1.1.4’



Would appreciate any pointers or help regarding troubleshooting the same.

Thank you
Zeenia Jagga

**Comment by p-smirnov** [comment]
It seems there was a capitalization error (False vs FALSE). However I cannot consistently reproduce on my machine, it behaves differently when called from RStudio vs Command Line. Zeenia, could you try to install the latest commit on your machine and see if the issue is resolved? 

Thank you

**Comment by Zeenia** [comment]
@p-smirnov I am still getting the same error on R studio, I tested on windows as well as Cent OS. On the other hand when I tested on R command line in centOS instead of Rstudio, this error did not appear, although there is this new error 
```
> GDSC.auc <- summarizeSensitivityProfiles(common$GDSC, sensitivity.measure=common$GDSC, sensitivity.measure='auc_published', summary.stat="median", add=TRUE)
Error in summarizeSensitivityProfiles(common$GDSC, sensitivity.measure = common$GDSC,  : 
  formal argument "sensitivity.measure" matched by multiple actual arguments
```

**Comment by bhaibeka** [comment]
Zeena, looks like you have the parameter 'sensitivity.measure' twice in your command. Can you make sure it appears only once?

**Comment by spocks** [comment]
Regarding the error
```
> commonGenes <- intersect(featureNames(GDSCsmall, "rna"), featureNames(CCLEsmall,"rna"))
Error in intersect(featureNames(GDSCsmall, "rna"), featureNames(CCLEsmall, :
error in evaluating the argument 'x' in selecting a method for function 'intersect': Error in featureNames(GDSCsmall, "rna") : unused argument ("rna")
```

Use `PharmacoGx::featureNames` 

```
commonGenes <- intersect(PharmacoGx::featureNames(GDSCsmall, "rna"), PharmacoGx::featureNames(CCLEsmall,"rna"))

```

This problem arises due to conflict in name of the function **featureNames** . _Biobase_ also have function **featureNames**  which conflict with  `PharmacoGx::featureNames`  (another reason for my eternal hate for R )

@p-smirnov We should consider changing name of this function!!

**Comment by p-smirnov** [comment]
@spocks It has already been changed to fNames.
