### ISSUE TITLE
pre-built PharmacoSet objects

### ISSUE THREAD

**Issue by lwaldron** [bhklab/PharmacoGx#13]
Can you point us to any pre-built objects? And perhaps create a link to them in the README.md file.

**Comment by bhaibeka** [comment]
You can use the availablePSets() and downladPSet() functions

`availablePSets()

trying URL 'https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/PSets.csv'
Content type 'text/csv' length 1776 bytes
==================================================
downloaded 1776 bytes

                      PSet.Name Dataset.Type Available.Molecular.Profiles
CCLE_2013             CCLE_2013  sensitivity                 rna/mutation
CCLE                       CCLE  sensitivity      rna/rnaseq/mutation/cnv
GDSC_2013             GDSC_2013  sensitivity                 rna/mutation
GDSC                       GDSC  sensitivity rna/rna2/mutation/fusion/cnv
GDSC1000               GDSC1000  sensitivity                          rna
gCSI                       gCSI  sensitivity                   rnaseq/cnv
FIMM                       FIMM  sensitivity                             
CTRPv2                   CTRPv2  sensitivity                             
CMAP                       CMAP perturbation                          rna
L1000_compounds L1000_compounds perturbation                          rna
L1000_genetic     L1000_genetic perturbation                          rna

> gCSI <- downloadPSet("gCSI")

trying URL 'https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/PSets.csv'
Content type 'text/csv' length 1776 bytes
==================================================
downloaded 1776 bytes

trying URL 'https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/gCSI.RData'
Content type 'unknown' length 120395992 bytes (114.8 MB)
==================================================
downloaded 114.8 MB`

**Comment by lwaldron** [comment]
Very nice functions!!
