### ISSUE TITLE
summarizeSensitivityProfiles not working, similar to issue#124

### ISSUE THREAD

**Issue by cicGuoH** [bhklab/PharmacoGx#130]
sorry, I'm new. Content is below.

**Comment by cicGuoH** [comment]
Hello, I was trying to use function `summarizeSensitivityProfiles` and I got this error similar to #124 . I followed the suggestions below that I first downloaded the PSet, however, error is still here. Here is my code.

```R
# CCLE <- downloadPSet("CCLE_2015", saveDir = "../Data/PharmacoGx")
CCLE <- readRDS("../Data/PharmacoGx/CCLE_2015.rds")
ccle.acc <- PharmacoGx::summarizeSensitivityProfiles(
  pSet=CCLE,
  sensitivity.measure='aac_recomputed',
  verbose=TRUE)
```

The error information is:
```R
Error in (function (classes, fdef, mtable)  : 
  函数‘summarizeSensitivityProfiles’标签‘"missing"’找不到继承方法
```
I think its version in english is 
```
Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘summarizeSensitivityProfiles’ for signature ‘"missing"’
```

**Comment by ChristopherEeles** [comment]
Hi @cicGuoH,

The argument name for passing a `PharmacoSet` into many of our functions have changed from `pSet` to `object`. This allows us to reuse these methods in other packages such as `ToxicoGx` and `RadioGx`, which have their own respective classes (`ToxicoSet` and `RadioSet`).

Our documentation has been updated to reflect these changes: https://bioconductor.org/packages/devel/bioc/vignettes/PharmacoGx/inst/doc/PharmacoGx.html. Perhaps you are following an old tutorial?

Either way, this should work:
```
ccle.acc <- PharmacoGx::summarizeSensitivityProfiles(
  object=CCLE,
  sensitivity.measure='aac_recomputed',
  verbose=TRUE)
```

If you still get the error, please try printing out your `PharmacoSet` variable to make sure it loaded correctly.

Best,
Christopher Eeles
Software Developer
Haibe-Kains Lab
PMCC | UHN

**Comment by cicGuoH** [comment]
Thank you very much. I changed from `PSet` into `object` and it works. Sorry for my carelessness.
