### ISSUE TITLE
not download CMAp

### ISSUE THREAD

**Issue by Zhengly-FMU** [bhklab/PharmacoGx#143]
![image](https://user-images.githubusercontent.com/59169918/227955576-fdf6b21a-deba-4a47-ac38-29edccaa8764.png)
I found that I could not get the CMAP data in the availablePSets

**Comment by jjjermiah** [comment]
Hi,
we have a subset of our PharmacoSets we refer to as "canonical". These are the ones retrieved when running availablePSets(), where the parameter `canonical=TRUE` by default. By passing `canonical=FALSE ` i.e `availablePSets(canonical=FALSE)`, all of the PharmacoSets will be displayed. The correct PSet Name for CMAP is `CMAP_2016` so it can be downloaded by `downloadPSet("CMAP_2016")`. 

Please let me know if that works. 

Jermiah
