### ISSUE TITLE
NCI60 PharmacoSet is different

### ISSUE THREAD

**Issue by KatynaSada** [bhklab/PharmacoGx#148]
Hi! The NCI60 PharmacoSet does not have a 3D array containing raw data in $raw , it has a data.frame containing sensitivity profile statistics which is supposed to be in $profiles.  When I try to create the drugDoseResponseCurve I get an error (Error in if (drop) { : argument is not interpretable as logical)), and I guess it is for this reason.

**Comment by jjjermiah** [comment]
Hi, 

Thank you for raising this issue. We believe this error is from a recent update to the scripts that generate the PSETS and have reverted to a previous version of the dataset object on Orcestra. Please let us know if re-downloading the PSET fixes this issue for you.

**Comment by KatynaSada** [comment]
Yes, by downloading the object from Orcestra (and not the R package) and updating it using updateObject. Thanks
