### ISSUE TITLE
Error in Intersecting GDSC and CCLE Psets

### ISSUE THREAD

**Issue by OrysyaStus** [bhklab/PharmacoGx#5]
Hello. I recently started using this R package and prior to using it to mine my own data, I wanted to reproduce the data which was published in "PharmacoGx: an R package for analysis of large pharmacogenomic datasets." using the code produced in the supplementary information: [https://github.com/OrysyaStus/ProQinase/blob/master/PharmacoGx/pharmacogx_supp_info.pdf](url) which I made into my own .R file [https://github.com/OrysyaStus/ProQinase/blob/master/PharmacoGx/Pharmacogx_practice.R](url). 

I have started to run the code on R 3.3.1 on Linux 64x as well as on Windows, but am having the same error come up when I run lines 28-32:
`myfn <- file.path(sprintf("common_GDSC_CCLE_PSet.RData"))
if (!file.exists(myfn)) {
    common <- intersectPSet(pSets = list("CCLE"=CCLE, "GDSC"=GDSC), intersectOn = c("cell.lines", "drugs", "concentrations"))
    save(list = c("common"), compress = TRUE, file = myfn)
} else {load(myfn)}`

The error is:
Intersecting large PSets may take a long time ...
Error in which.min(abs(as.numeric(doses[[i]]) - min.dose)):max(which(abs(as.numeric(doses[[i]]) -  : 
  result would be too long a vector
In addition: Warning message:
In max(which(abs(as.numeric(doses[[i]]) - max.dose) == min(abs(as.numeric(doses[[i]]) -  :
  no non-missing arguments to max; returning -Inf

Any suggestions as to how to get past this error? Thanks.

**Comment by p-smirnov** [comment]
Dear Orysya,

I apologize for the inconvenience, I remember fixing this bug but it seems like I missed pushing it onto github!

Could you reinstall PharmacoGx from github as below and try again?

`install_github('bhklab/PharmacoGx')`

Thank you!
Petr

**Comment by OrysyaStus** [comment]
Thanks Petr. It's working great now.

Best,
Orysya
