### ISSUE TITLE
can't reproduce the result of case study 2 from publication

### ISSUE THREAD

**Issue by yeaouh** [bhklab/PharmacoGx#50]
I tried to reproduce the code in the supplementary data of the paper "PharmacoGx: an R package for analysis of large pharmacogenomic datasets",which I made into my own .R file https://github.com/yeaouh/graduation/blob/master/R/HDAC.R. I ran the code without modifying any part of it, but I can't reproduce the result of case study 2 in this paper. The result in the paper said that the four known HDAC inhibitors (vorinostat、trichostatin A、HC toxin、valproic acid) are ranked in the top eight drugs according to CMAP connectivity scores, just like the figure below shows:
![result in paper](https://user-images.githubusercontent.com/42791882/55768667-5a76f480-5ab0-11e9-94f0-2dfa0606164a.JPG)
But the result I got by running the code is a bit different. The connectivity score of HC toxin is 0.5451 and the connectivity scores of the other three are 0.The details are shown in the figures below:
![HC toxin](https://user-images.githubusercontent.com/42791882/55768766-bf324f00-5ab0-11e9-8ba9-1236da862364.JPG)
![valproic acid](https://user-images.githubusercontent.com/42791882/55768775-c5283000-5ab0-11e9-9861-752400724835.JPG)
![trichostatin A](https://user-images.githubusercontent.com/42791882/55768780-c8bbb700-5ab0-11e9-93ec-00b543d4c4ff.JPG)
![vorinostat](https://user-images.githubusercontent.com/42791882/55768789-cbb6a780-5ab0-11e9-90b2-a38b746e19cf.JPG)

Any suggestions as to how to circumvent this error and produce the correct results?

Thank you.

**Comment by bhaibeka** [comment]
Thanks for reaching out. I have rerun your code with the last version of PharmacoGx
`devtools::install_github("https://github.com/bhklab/PharmacoGx")`

And got the expected results
[HDAC_res_table.pdf](https://github.com/bhklab/PharmacoGx/files/3100325/HDAC_res_table.pdf)
[HDAC_res_v1_table.pdf](https://github.com/bhklab/PharmacoGx/files/3100326/HDAC_res_v1_table.pdf)

These are not exactly the same than in the initial publication as we have improved the normalization of the CMAP data but the change is quite minor.
