### ISSUE TITLE
Error when intersecting PSets and plotting dose response curves

### ISSUE THREAD

**Issue by FarzanT** [bhklab/PharmacoGx#51]
Hello,
I couldn't find an issue discussing the error I receive below, when trying to find the intersection between the three pSets on drugs and cell.lines with strictIntersect.
```r
ccle <- PharmacoGx::downloadPSet("CCLE_2013")
gdsc <- PharmacoGx::downloadPSet("GDSC_2013")
gcsi <- PharmacoGx::downloadPSet("gCSI")

common = intersectPSet(pSets = list(ccle, gdsc, gcsi),
                       intersectOn = c("drugs", "cell.lines"), strictIntersect = T, nthread = 2)

Intersecting large PSets may take a long time ...
Error in pSet@sensitivity$raw[exps, , , drop = drop] : 
  incorrect number of dimensions
```
Changing it to drugs only works:
```r
common = intersectPSet(pSets = list(ccle, gdsc, gcsi),
                       intersectOn = "drugs", strictIntersect = T, nthread = 2)
```
I am trying to ensure that the intersection contains the same cell lines with the same tested drugs, but I am uncertain if the second chunk of code has this desired effect.

A similar error message appears below, and the following lines of code result in the different errors:
```r
drugDoseResponseCurve(drug = "Lapatinib", cellline = "HARA",
                      pSets = ccle)
NULL
Warning message:
In drugDoseResponseCurve(drug = "Lapatinib", cellline = "HARA",  :
  The cell line and drug combo were not tested together. Aborting function.

drugDoseResponseCurve(drug = "lapatinib", cellline = "HARA",
                      pSets = ccle)
Error in pSets[[i]]@sensitivity$raw[exp_i, , "Dose"] : 
  incorrect number of dimensions
```
Where one has the drug name in lower case and the other in uppercase. I am certain the _lapatinib_ was tested in the _HARA_ cell line, as indicated by the following function calls:
```r
cell_drug <- sensNumber(ccle)
cell_drug <- as.data.table(cell_drug, keep.rownames = T)
breast_cells <- ccle@cell$cellid[ccle@cell$tissueid == "breast"]
# All the cell lines in CCLE that have a breast origin and test Lapatinib
cell_drug[rn %in% breast_cells & lapatinib == 1]$rn
 [1] "AU565"          "BT-20"          "BT-474"         "BT-549"         "CAL-85-1"       "CAMA-1"        
 [7] "EFM-19"         "HARA"           "HCC1187"        "HCC1395"        "HCC1569"        "HCC1806"       
[13] "HCC1954"        "HCC70"          "HDQ-P1"         "HMC-1-8"        "Hs 739.T"       "MB 157"        
[19] "MCF7"           "MDA-MB-157"     "MDA-MB-175-VII" "MDA-MB-415"     "MDA-MB-436"     "MDA-MB-453"    
[25] "MDA-MB-468"     "SK-BR-3"        "UACC-812"       "ZR-75-1"        "ZR-75-30"      
```
_HARA_ is the 8th in the list above.
Please let me know if this is the wrong way of accessing the PSets/using the package.

Thank you!
Farzan

**Comment by p-smirnov** [comment]
@FarzanT Just got back from vacation, will take a look and try to see what happened in the next few days!

**Comment by p-smirnov** [comment]
Hi @FarzanT,

There is a bit of oversight in the error handling of the functions, and they aren't providing useful error messages. Thank you for highlighting this! 

The issues you are running into all stem from the fact that neither CCLE_2013 or GDSC_2013 have any drug-dose response curve data in the PSets. In 2013, the studies have not yet released the concentration-viability pairs that would allow us to plot the curves and recalculate statistics. 

Strictly speaking, the intersection of the PSets should work and this is a bug. The drug dose response curve however has nothing to plot!

I would recommend switching to the non-2013 versions of these PSets - especially to visualize the actual data. 

Best,
Petr
