### ISSUE TITLE
error in checkPsetStructure

### ISSUE THREAD

**Issue by spocks** [bhklab/PharmacoGx#70]
Here `colData` should be used instated of `rowData`

https://github.com/bhklab/PharmacoGx/blob/d91bf140a4ea3faac30c30509c1c7f173560d7af/R/class-PharmacoSet.R#L369

Correct code:
`if('cellid' %in% colnames(colData(profile))) {`

**Comment by ChristopherEeles** [comment]
I will look into this today. Thanks for opening the issue.

**Comment by ChristopherEeles** [comment]
I have made the changes in master and RELEASE_3_11. Both branches have also been pushed to Bioconductor.

Thanks for catching that.

Best,
Christopher Eeles
