### ISSUE TITLE
normalization method of RNA-Seq data

### ISSUE THREAD

**Issue by zhumengyan** [bhklab/PharmacoGx#76]
Thanks for your great tools!
I have download GDSC2 (2020) from ORCESTRA. 
I found that data in GDSC@molecularProfiles$Kallisto_0.46.1.rnaseq has negative value. So Could you provide some details about data processing?

**Comment by zhumengyan** [comment]
Moreover, I can't find ic50_published info in sensitivity profiles

**Comment by ChristopherEeles** [comment]
Hi @zhumengyan,

Sorry for the slow response. Can you confirm that this is still an issue by downloading the PSet from ORCESTRA again?

If it is would you open an issue here: https://github.com/bhklab/ORCESTRA

All the PharmacoSet are created and version controlled via ORCESTRA.

Thanks,
Chris
