### ISSUE TITLE
Error creating new PharmacoSet

### ISSUE THREAD

**Issue by kevincjnixon** [bhklab/PharmacoGx#78]
Hello,

I am trying to incorporate new gene expression data from the Affymetrix Human Gene 2.0 ST microarray into the existing CMAP_2016 PharmacoSet. I am pulling the individual slots from the existing PSet and appending the new data to each slot and attempting to rebuild the PSet with the new data. 

I have successfully created the `SummarizedExperiment` object ('mp' below) with all mandatory rowData and colData columns (as outlined in the PharmacoGx vignette for the `PharmacoSet()` function). I have also updated the cell, drug, and curation data to include the new drug/cell line info.

When I run 

`PharmacoSet("newCMAP", molecularProfiles=list(rna = mp), cell=cell, drug=drug, curationDrug=curation$drug, curationCell=curation$cell, curationTissue=curation$tissue, datasetType="perturbation", verify=T)`  

I receive the following error:

```
 Error in `[<-`(`*tmp*`, rownames(tt), colnames(tt), names(object@molecularProfiles)[i],  : 
  subscript out of bounds
In addition: Warning messages:
1: In checkPsetStructure(pSet) : rna: rowData dimension is OK
2: In checkPsetStructure(pSet) : rna: colData dimension is OK
3: In checkPsetStructure(pSet) : 
4: In checkPsetStructure(pSet) : 
5: In checkPsetStructure(pSet) : BEST is OK
6: In checkPsetStructure(pSet) : Symbol is OK
```
I am hoping that you might be able to tell me what could be the cause of this error. 

To give a little more detail: 
The new data had fewer genes than the original PSet, and so the resulting `SummarizedExperiment` object was reducted to 11,451 genes (from 11,833) and increased to 7,065 columns (samples) from 7,056. The rowData used in the new SE object was the same as that from the original PSet (minus the removed genes), and the colData has only the 6 mandatory columns as indicated by the vignette (cellid, batchid, drugid, duration, concentration, xptype). Information for 1 cell line was added to the cell slot, and information on 2 drugs was added to the drug slot. I followed the same formatting to generate the curation data.frames with the updated cell/drug data. 

Below is the `sessionInfo()`. Please let me know if there is anything else you need.

Thank you!

![image](https://user-images.githubusercontent.com/60985228/108111312-85461280-7062-11eb-8467-3f2301f5f3a1.png)

**Comment by ChristopherEeles** [comment]
Hi @kevincjnixon,

Thanks for opening the issue. It looks like an error in an assignment operator within the constructor. I will look into it and let you know if I need more information.

Best,
Chris

**Comment by ChristopherEeles** [comment]
Hi @kevincjnixon,

I have narrowed down the problem to the `PharmacoGx:::.summarziePeturbationNumbers` function. 

The code is as follows:
```
.summarizePerturbationNumbers <- function(object) {

  if (object@datasetType != 'perturbation' && object@datasetType != 'both') {
    stop ('Data type must be either perturbation or both')
  }

  ## consider all drugs
  drugn <- rownames(object@drug)

  ## consider all cell lines
  celln <- rownames(object@cell)

  perturbation.info <- array(0, dim=c(length(celln), length(drugn),
      length(object@molecularProfiles)), dimnames=list(celln, drugn,
      names((object@molecularProfiles))))

    for (i in seq_len(length(object@molecularProfiles))) {
      if (nrow(SummarizedExperiment::colData(object@molecularProfiles[[i]])) > 0 && 
          all(is.element(c('cellid', 'drugid'), colnames(SummarizedExperiment::colData(object@molecularProfiles[[i]]))))) 
      {
        tt <- table(SummarizedExperiment::colData(object@molecularProfiles[[i]])[ , 'cellid'], 
          SummarizedExperiment::colData(object@molecularProfiles[[i]])[ , 'drugid'])
        perturbation.info[rownames(tt), colnames(tt), names(object@molecularProfiles)[i]] <- tt
      }
    }

    return(perturbation.info)
}
``` 

The error is occuring in ` perturbation.info[rownames(tt), colnames(tt), names(object@molecularProfiles)[i]] <- tt`. SInce the error  indicates subscript out of bound, one of two things is happening:

1. The rownames of the cell table do not match the values of the 'cell_id' column in `colData` of your SummarizedExperiment
2. The rownames of the drug table do not match the values of the 'drug_id' column in the `colData` of your SummarizedExperiment.

You can try stepping debugging the function in RStudio by setting `debugonce(PharmacoGx:::..summarizePerturbationNumbers)` before running the constructor. That should open an interactive browser so you can see what is going wrong in the function.

If this does not resolve your issue please let me know. It is likely I could need a copy of your data to debug the issue further.

Best,
Chris

**Comment by kevincjnixon** [comment]
@ChristopherEeles 
Thank you so much for your help. I will look into this and let you know if there are any other issues.

Best,

Kevin

**Comment by kevincjnixon** [comment]
@ChristopherEeles 
I found the problem, I wasn't included the 'NA' for drug controls in the updated drug table for the PSet. Thank you very much for your help!
