### ISSUE TITLE
Error in `inconsistencies` vignette chunk

### ISSUE THREAD

**Issue by LiNk-NY** [bhklab/PharmacoGx#9]
Hi @p-smirnov, 
A recent patch to `Biobase` has created an error in the vignette. The error originates from the `summarizeMolecularProfiles` function. 
I have a fix for this.

**Comment by bhaibeka** [comment]
Hi Marcel,

Do you want me to add you as a collaborator or do you want to send the new code?

**Comment by LiNk-NY** [comment]
Hi @bhaibeka, 
I think this error has been addressed. 
Thanks.
