### ISSUE TITLE
The Range of ic50_recomputed

### ISSUE THREAD

**Issue by AlirezaShokrollahi** [bhklab/PharmacoGx#92]
Hello 
I wrote this code to extract ic50_recomputed for all cell lines in GDSC_2020(v2-8.2):
summarizeSensitivityProfiles(GDSC, sensitivity.measure="ic50_recomputed", summary.stat="median")
IC50 values were very unusual. for example maximum of IC50 in HC-1 cell line is 1.512456e+17 and minimum of IC50 in HC-1 cell line is 1.042329e-06. 
Why is there such a difference between these values? Are these values true?
Thank you.

**Comment by p-smirnov** [comment]
Hi Alizera,

The IC50 values will have a very large range, especially across different drugs for one cell line, for a couple of reasons:

The first is that they are inferred from the curve fit to the dose-response data, and can be extrapolated above and below the actual concentration range tested. If you wish, you can truncate them or censor them to lie within the tested concentration range for each experiment by looking at the raw sensitivity array. 

The second is that you’re comparing across drugs which have very different potency, often across several orders of magnitude. Even after truncation, I would recommend analyzing this data on a logarithmic scale. 

All the best,
Petr

**Comment by AlirezaShokrollahi** [comment]
Hi Petr
Thank you very much.
